
TRIAL = "liart.rallydev.com"
PROD  = "officialness.rallydev.com"

TRIAL_USER = "usernumbernonei@acme.com"
TRIAL_PSWD = "B1G^S3Kretz"
TRIAL_NICKNAME = "Wiley"

DEFAULT_WORKSPACE    = "Your Default Workspace"
DEFAULT_PROJECT      = "Your Default Project"
NON_DEFAULT_PROJECT  = "A non-default Project"
ALTERNATE_WORKSPACE  = "An Alternate Workspace"
#ALTERNATE_PROJECT   = "Dynamic"
ALTERNATE_PROJECT    = "An Alternate Project"

API_KEY = "_ABC123DEF456GHI789JKL012MNO345PQR678STU901VWXZ"

HTTPS_PROXY = "127.0.0.1:3128"

__all__ = [TRIAL, TRIAL_USER, TRIAL_PSWD, TRIAL_NICKNAME, PROD, 
           DEFAULT_WORKSPACE, DEFAULT_PROJECT, 
           NON_DEFAULT_PROJECT, ALTERNATE_WORKSPACE, ALTERNATE_PROJECT, HTTPS_PROXY]
